### ISSUE TITLE
Update rbcexample for new interface

### ISSUE THREAD

**Issue by donskerclass** [HighDimensionalEconLab/DifferentiableStateSpaceModels.jl#121]
To test out the code, I attempted to run the notebook [rbcexample.ipynb](https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/rbc_example.ipynb)  but as unable to get it to run.  

The error was "UndefVarError: DefinedNoise not defined": looking into this, it seems that DifferenceEquations.jl in its current iteration has a completely different interface, so the way it is called in this example code is incompatible with it in multiple ways.  Since that package has no docs, it would be helpful to update the code in this example notebook to be compatible with it, both so that people have a working notebook and as a syntax example.

As I understand it, the examples in [HMCExamples.jl](https://github.com/HighDimensionalEconLab/HMCExamples.jl) do use the current interface (at least, that code runs). If so, I will check that to see if I can figure out the changes needed to get this notebook working again.

**Comment by jlperla** [comment]
Yes, we will update that after we verify everything is correct for the HMCExamples interface.  There will also be some changes to the DifferenceEquations that we will want to merge first.  The first step was getting the HMCExamples tested with examples though.

**Comment by donskerclass** [comment]
Yeah, no rush on this, I didn't mean to interrupt you. I was just looking for some basic code examples so that I can test out new models on my own in a notebook.  I will follow the HMCExamples code for now, and we'll keep this issue open to remind us to fix it when the interface does stabilize.

**Comment by jlperla** [comment]
Note: should add in new manifest and put in subfolder since Turing is no longer a dependency.

**Comment by jlperla** [comment]
Closing for new issue with more details.
