### ISSUE TITLE
Steps for FVGQ gradients debugging

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/DifferentiableStateSpaceModels.jl#124]
- [ ] #114 lets us see if this use to work or has always been an issue.  @wupeifan
- [x] Add `H_p` check to the symbolic gradient verificaiton.  @jlperla 
- [x] Add `ȳ_p` and `x̄_p` to the symbolic gradient verifciation.  @jlperla 
- [x] Drop the conditional in https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/src/generate_perturbation_derivatives.jl#L93-L101  and see if it helps to use `H_p` instead. @jlperla 
- [x] Try to see if the `buff` itself has a bug.
  - Drop the whole of the `buff.` in the calculations inside https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/src/generate_perturbation_derivatives.jl#L85-L166  @jlperla 
- [x] Try the old Sylvester solver instead of https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/src/generate_perturbation_derivatives.jl#L137  @wupeifan 
- [x] Methodically go through the algebra for the preparation of the dH, R, E, C, A, etc. in https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/src/generate_perturbation_derivatives.jl#L110-L139  to look for typos relative to the algebra (e.g. a `n_y` or `n_x` mistake, a missing transpose, etc. that might not be relevant given sparsity pattern of RBC, etc.)  @wupeifan

**Comment by wupeifan** [comment]
Basically the old Sylvester solver works. I think I've also find an issue in Michel's package which overwrites a bunch of input variables.
