### ISSUE TITLE
Get rid of Plots and StatsPlots dependencies

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/DifferentiableStateSpaceModels.jl#32]
@cpfiffer  Thoughts?  This would remove some troublesome dependencies.

These can be test dependencies if we wish, but not core ones.  To do this, I think we need to:
- [ ] From the main package: `]rm Plots StatsPlots TuringCallbacks`  and also remove the `compat`: https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/Project.toml#L44  etc.
- [ ] And in the unit tests, I think we can also get rid of this stuff as well... leave the callbacks for downstream users:
  - i.e., in https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/test/Project.toml  we can remove `TuringCallbacks, StatsPlots, TensorBoardLogger`?  Though this I feel a little less sure about....

Then 
- [ ] Get this out of the package: https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/src/turing_utils.jl
  - It was there temporarily, and should be removed regardless
- [ ] Get rid of all turingcallbacks, etc. in https://github.com/HighDimensionalEconLab/DifferentiableStateSpaceModels.jl/blob/main/test/rbc_estimation.jl#L48
  - Also get rid of the `use_tensorboard` and all callbacks.

**Comment by wupeifan** [comment]
It's a bit strange that the error message from CI still reports as missing TuringCallbakcs, even though I've removed it everywhere...
