### ISSUE TITLE
Update deprecated chainrules usage 

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/DifferentiableStateSpaceModels.jl#33]
See the warnings
```
WARNING: ChainRulesCore.Composite is deprecated, use Tangent instead.
  likely near C:\Users\jesse\Documents\GitHub\HMCExamples.jl\test\runtests.jl:7
WARNING: ChainRulesCore.Composite is deprecated, use Tangent instead.
  likely near C:\Users\jesse\Documents\GitHub\HMCExamples.jl\test\runtests.jl:7
in kw_zpullback at C:\Users\jesse\.julia\packages\Zygote\ggM8Z\src\compiler\chainrules.jl
```

Not sure where we are using it, though, since it isn't used directly.  Maybe upstream or something coming out of a a conversion in our sole `rrule`?

**Comment by wupeifan** [comment]
The ChainRules maintenance guys have renamed a bunch of variables, for example renaming the derivative as Tangent and renaming a zero-object as ZeroTangent in the latest ChianRule versions, I think. It possibly will change some of the `if-else` in the DSSM package.

**Comment by jlperla** [comment]
Sure, but I am not sure where we are using this dierctly.  I suspect it is upstream or happening due to an automatic propotion from `nothing` or something along those lines.
