### ISSUE TITLE
Deepcopy of the module

### ISSUE THREAD

**Issue by jlperla** [HighDimensionalEconLab/DifferentiableStateSpaceModels.jl#70]

**Comment by jlperla** [comment]
For now, add the following
```julia
import Base.deepcopy_internal
deepcopy_internal(x::Module,stackdict::IdDict) = x
```
Note that this basically makes Module's shallow copy.  i.e., treats them as references.  This is very unlikely to cause issues globally since right now it errors.

I tried to see if tehre was a way to "stop" the recursiion to copy a weak reference but it doesn't seem immediately possible.  Later we can revisit this hack.

**Comment by jlperla** [comment]
This is triggering a compilation warning, so we should revsit at some point:
```
[ Info: Precompiling DifferentiableStateSpaceModels [beacd9db-9e5e-4956-9b09-459a4b2028df]
WARNING: Method definition deepcopy_internal(Module, Base.IdDict{K, V} where V where K) in module Base at deepcopy.jl:33 overwritten in module DifferentiableStateSpaceModels at c:\Users\jesse\Documents\GitHub\DifferentiableStateSpaceModels.jl\src\types.jl:2.
  ** incremental compilation may be fatally broken for this module **
```

**Comment by wupeifan** [comment]
Yeah, essentially we overrode that line in `deepcopy.jl`

**Comment by cpfiffer** [comment]
Def. low priority for now, or at least it seems that way. One performance hit we could be exposing ourself to is that we're overwriting a fairly core Julia function, which could trigger a bunch of recompilations. Either way, the hit we're taking is at JIT spinup time and not runtime, so I'm not terribly worried for now.

**Comment by jlperla** [comment]
Exactly.  Yeah, this was intended as a hack to get us through, and we would need to revsit.  What I didn't realize was that it was overwriting anything - rather than just adding in something that didn't already exist.  But I don't think it will cause any immediate issues with the runtime.

The other things I tried (e.g. storing a `Ref{Module}` had the same problems since it didn't seem like there was any other convenient way to stop the recusion without a custom type.

So the next stage in the hack is to add in a wrapper `DontDeepCopyMe{Module}` which stops the deepcopy recusiion at the custom type so then piracy is required.  But this whole thing was just temporary anyways, so we shall see.
